openapi: 3.0.3
info:
  title: NanoUrl
  description: Web API for creating short URL. Built with C# .NET framework.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0'
servers:
- url: https://nan1.azurewebsites.net/
  description: NanoUrl Production Server (live data)
paths:
  /:
    get:
      summary: Retrieve the base URL of the NanoUrl server
      tags:
        - NanoUrl
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /{shortCode}:
    get:
      summary: Redirect to the original URL associated with a given short code
      tags:
        - Url
      parameters:
        - name: shortCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /get/{shortCode}:
    get:
      summary: Fetch the original URL mapped to a specified short code
      tags:
        - Url
      parameters:
        - name: shortCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UrlMap'
            application/json:
              schema:
                $ref: '#/components/schemas/UrlMap'
            text/json:
              schema:
                $ref: '#/components/schemas/UrlMap'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /custom:
    post:
      summary: Create a custom short URL for a provided long URL
      tags:
        - Url
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlMap'
          text/json:
            schema:
              $ref: '#/components/schemas/UrlMap'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UrlMap'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /shorten:
    post:
      summary: Generate a short URL for a given long URL
      tags:
        - Url
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      additionalProperties: false
    UrlMap:
      type: object
      properties:
        id:
          type: string
          nullable: true
        original:
          type: string
          nullable: true
        shortCode:
          type: string
          nullable: true
      additionalProperties: false
